[package]
name = "naskah"
version = "0.1.0"
authors = ["Fatih Kalifa <fatihkalifa@gmail.com>"]

[dependencies]
lazy_static = "1.1.0"
nom = { version = "^4.1.0", features = ["regexp", "regexp_macros"] }
regex = "1.0.5"